export const TIPOS_VEICULO_CARRO = [
  'Troca de óleo + filtro de óleo',
  'Troca de óleo + filtro de combustível + filtro de gasolina',
  'Troca de óleo + filtro de combustível + filtro de gasolina + filtros de ar',
  'Alinhamento e balanceamento',
  'Troca de pneus',
  'Revisão de freios',
  'Troca de filtro de ar',
  'Revisão elétrica',
  'Revisão de bateria',
  'Ar condicionado',
  'Funilaria e pintura',
  'Troca de velas',
  'Revisão de suspensão',
  'Higienização',
  'Rodízio de pneus',
  'Troca correia dentada',
  'Revisão pastilhas de freio',
  'Motor',
  'Câmbio',
  'Radiador',
  'Descarga',
  'Embreagem',
  'Direção',
  'Vencimento seguro',
  'Vencimento IPVA',
  'Licenciamento',
  'Outro',
]

export const TIPOS_VEICULO_MOTO = [
  'Troca de óleo + filtro de óleo',
  'Kit relação (corrente, coroa e pinhão)',
  'Sistema de freios (pastilhas, sapatas e fluido)',
  'Bateria',
  'Motor',
  'Revisão freios',
  'Funilaria e pintura',
  'Cabos embreagem, freios, acelerador',
  'Troca de velas',
  'Vencimento seguro',
  'Vencimento IPVA',
  'Licenciamento',
  'Outro',
]
